Speedup source map plugin
Khan/webpack pull request #1
Opened 2019-01-18 18:28 UTC by kevinbarabash

**What kind of change does this PR introduce?**

This PR adds a new feature.  In particular it adds a `skipExistingFiles` option to `SourceMapDevToolPlugin` which skips generating source maps for bundles whose source map files already exist on disk.  This setting should be used with `DisableEmitPlugin`.  This setting is not compatible with inline source maps.

**Did you add tests for your changes?**

Not yet.

**Does this PR introduce a breaking change?**

It should not because the new behavior is behind a new configuration option to SourceMapDevToolPlugin.

**What needs to be documented once your changes are merged?**

The only thing that needs documentation is the new `skipExistingFiles` option.

**Test Plan**

- Update webapp's wepback.prod.config to replace the `devtool` setting with an explicit `SourceMapDevToolPlugin` like so:
```
// Generate sourcemaps.
            // See https://webpack.js.org/plugins/source-map-dev-tool-plugin/.
            new webpack.SourceMapDevToolPlugin({
                module: true,
                // Quicker to generate but doesn't allow setting breakpoints
                // on columns or stepping through statements within the same
                // line.
                columns: false,
                // Simplify and speed up source mapping by using line to line
                // source mappings for matched modules.
                lineToLine: true,
                noSources: false,
                // Generates discrete files containing the source maps.
                // NOTE: currently we only support replacing "[file]".
                filename: "[file].map",
                // This setting is ignored if `filename` is undefined.
                skipExistingFiles: true,
            }),
```
- run `yarn build:webpack-prod-profile --no-i18n` in webapp
- see `36ms after chunk asset optimization` in the output
- run `yarn test` in webpack and see that all the tests pass
<img width="985" alt="screen shot 2019-01-18 at 5 54 12 pm" src="https://user-images.githubusercontent.com/1044413/51418687-f8fb5580-1b52-11e9-99d9-0b40d8273bd2.png">

2019-01-18 18:29 UTC, k4b7 commented on lib/SourceMapDevToolPlugin.js
> +const doesOutputFileExist = (filename, compilation) => {
@jeresig I'm not sure how to share this function with other plugins.

2019-01-18 19:37 UTC, jeresig submitted a review, later dismissed
Thank you for working on this, Kevin! I've left a lot of thoughts inline. Let me know if you have any questions!

2019-01-18 19:37 UTC, jeresig commented on lib/SourceMapDevToolPlugin.js
> +								if (options.skipExistingFiles && sourceMapFilename) {
I think we need to add a check to see if we even want to be outputting a sourcemap file in the first place - or is that what `sourceMapFilename` is?

2019-01-18 19:37 UTC, jeresig commented on lib/SourceMapDevToolPlugin.js
> +								if (options.skipExistingFiles && sourceMapFilename) {
I think we should move most of this logic out into a separate function. Then we can just have:

```
if (matchObject(file) && shouldGenerateSourceMap(file, sourceMapFilename, options)) {
```

(or some such).

2019-01-18 19:37 UTC, jeresig commented on lib/SourceMapDevToolPlugin.js
> +									const filename = file;
I'm finding all of these different "file" variables to very confusing. I would appreciate reducing them, giving them more-descriptive names, and adding comments! (For example I don't think you need to re-name `file` here, you can just use it.)

2019-01-18 19:37 UTC, jeresig commented on lib/SourceMapDevToolPlugin.js
> +									if (doesOutputFileExist(sourceMapFile, compilation)) {
So what I was thinking was that instead of passing in `skipExistingFiles` you would instead pass in the function that you have here, something like: `options.shouldGenerateMapFile(filename, sourceMapFile)` or some such - providing all the information that should be needed and it's expected that it would just return true/false (the specific qualification for why we should keep a file would be left up to the function).

2019-01-18 19:37 UTC, jeresig commented on lib/SourceMapDevToolPlugin.js
> +										compilation.assets[sourceMapFile] = new RawSource("");
Hmm - so I think the only reason why this is working is because we're also already using the DisableEmitPlugin that I wrote. You could update it here to set the `existsAt` property for the output directory file and that would make it not output (and would also make it so that people didn't need to use the DisableEmitPlugin).

2019-01-18 19:37 UTC, jeresig commented on lib/SourceMapDevToolPlugin.js
> -							let query = "";
All of this is largely duplicated above - it seems like we should probably move all of it into a function and just pass in a couple variables (filename, compilation, sourceMapFilename, options, sourceMapString) - and then we'd just not include the contentHash in our case since sourceMapString would be undefined.

2019-01-18 19:37 UTC, jeresig commented on package.json
> +    "webpack-cli": "^3.2.1",
Hmm - this seems like it shouldn't be here!

2019-01-18 20:45 UTC, kevinbarabash commented on lib/SourceMapDevToolPlugin.js
> +								if (options.skipExistingFiles && sourceMapFilename) {
That's what the `sourceMapFilename` check is for.  It's obfuscated a bit my the fact that `sourceMapFilename` is actually the same as `options.filename`.  In the docs it says if this isn't set then the sourcemaps will be inlined.

2019-01-18 20:46 UTC, kevinbarabash commented on lib/SourceMapDevToolPlugin.js
> +								if (options.skipExistingFiles && sourceMapFilename) {
will do

2019-01-18 20:47 UTC, kevinbarabash commented on lib/SourceMapDevToolPlugin.js
> +									const filename = file;
I find them confusing too.  I didn't tackle renaming them since I wanted to limit the scope of the changes in the hope that this could be upstreamed eventually.  I'll try to simplify them and we can worry about how to making this palatable to upstream maintainers later.

2019-01-18 20:54 UTC, kevinbarabash commented on lib/SourceMapDevToolPlugin.js
> +									if (doesOutputFileExist(sourceMapFile, compilation)) {
I'll give this a try.  I was worried about having too much SourceMapDevToolPlugin specific logic in our webpack config, but maybe that won't be the case.

2019-01-18 20:54 UTC, kevinbarabash commented on lib/SourceMapDevToolPlugin.js
> +										compilation.assets[sourceMapFile] = new RawSource("");
Good call.

2019-01-18 20:55 UTC, kevinbarabash commented on package.json
> +    "webpack-cli": "^3.2.1",
I'll revert this.

2019-01-18 23:06 UTC, kevinbarabash commented on lib/SourceMapDevToolPlugin.js
> +									const filename = file;
I haven't done this yet.

2019-01-18 23:32 UTC, jeresig requested changes
Ok, this generally seems good to me! Going to push back once more to get the logic broken out into a separate function to make it easier to understand.

2019-01-18 23:32 UTC, jeresig commented on lib/SourceMapDevToolPlugin.js
> +								let fileExists = false;
I think I would appreciate it if all of this new logic here was pulled out so that the check just became something like:

```
if (matchObject(file) && shouldGenerateSourceMap({sourceMapFilename, file, options, compilation})) {
    files.push({
        file,
        chunk
    });
}
```

Right now it's a lot of logic to follow this deeply-nested in the file!

2019-01-18 23:32 UTC, jeresig commented on lib/SourceMapDevToolPlugin.js
> +										compilation.assets[sourceMapFile].existsAt = targetPath;
Great!

2019-01-18 23:47 UTC, kevinbarabash commented on lib/SourceMapDevToolPlugin.js
> +								let fileExists = false;
Sorry, I shouldn't have dismissed this before.  Thanks for raising this again.  Will do!

2019-01-19 00:22 UTC, kevinbarabash commented on lib/SourceMapDevToolPlugin.js
> +								let fileExists = false;
This is done now.

2019-01-19 00:23 UTC, k4b7 commented
I still have to pick some better names for variables before we can land this.

2019-01-19 00:29 UTC, jeresig approved these changes
Ok, this is awesome - I think what you have right now makes a lot of sense to me. If you want to keep tweaking variables you're welcome to, but I think it's good in this form, too! Thank you.

2019-01-21 17:53 UTC, kevinbarabash commented
I'm going to leave the variable names for now.  If we need to do additional tweaks to this plugin I'l revisit the variable name issue then.

2019-01-21 17:53 UTC, merged